version: 2.1

orbs:
  architect: giantswarm/architect@4.0.0

executors:
  architect:
    docker:
      - entrypoint: /bin/bash
        image: quay.io/giantswarm/architect:4.0.0

jobs:
  go-build:
    executor: architect
    steps:
      - checkout
      - architect/tools-info
      - run: git clone https://github.com/kubernetes-sigs/cluster-api-provider-azure ./../cluster-api-provider-azure
      - architect/go-cache-restore
      - run: make test
      - architect/go-build:
          os: linux
          binary: capz-azure-admission-controller
      - architect/go-cache-save
      - persist_to_workspace:
          root: .
          paths:
            - ./capz-azure-admission-controller
workflows:
  build:
    jobs:
      - go-build:
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-capz-azure-admission-controller-to-quay
          image: "quay.io/giantswarm/capz-azure-admission-controller"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-capz-azure-admission-controller-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "capz-azure-admission-controller"
          requires:
            - push-capz-azure-admission-controller-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-capz-azure-admission-controller-to-azure-app-collection
          context: architect
          app_name: "capz-azure-admission-controller"
          app_namespace: "giantswarm"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-capz-azure-admission-controller-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
